KAFKA_BROKER = "localhost:9092"
RAW_TOPIC = "sensor.raw"

SENSOR_COUNT = 100

EVENTS_PER_SECOND = 10
LATE_EVENT_RATE = 0.10
DUPLICATE_EVENT_RATE = 0.05
MALFORMED_EVENT_RATE = 0.05

MAX_EVENT_DELAY_SECONDS = 20